# Generated by Django 4.0.10 on 2023-07-13 20:17

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_files',
            field=models.FileField(blank=True, null=True, upload_to=notes.models.upload_to),
        ),
    ]
